language: php

php:
 - '5.6'
 - '7.0'

env:
  matrix:
    - XDEBUG_VERSION=2.5.5

before_install:
 - pecl install xdebug-$XDEBUG_VERSION
 - phpenv config-add travis-php.ini
 - nvm install 7.4.0
 - nvm use 7.4.0
 - npm config -g set progress false

install:
 - npm install

script:
 - npm run compile --silent
 - npm run lint --silent
 - npm run cover --silent

after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && codecov'

after_script:
 - cat /tmp/xdebug.log

sudo: false
