language: php

php:
  - '7.1'
  - '5.6'
env:
  global:
    - NODE_VERSION=8.9.3
    - NPM_VERSION=^6.3.0
    - BUILD_LEADER_ID=4
  matrix:
    - XDEBUG_VERSION=2.5.5

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - chmod ugo+x ./scripts/travis-beforeinstall.sh
  - ./scripts/travis-beforeinstall.sh 'main'

install:
  - npm ci

script:
  - npm run build
  - npm run lint
  - npm run cover

after_success:
  - ./node_modules/.bin/nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode10.2
      language: generic
      before_install:
        - chmod ugo+x ./scripts/travis-beforeinstall.sh
        - ./scripts/travis-beforeinstall.sh 'test'
    - stage: release
      language: node_js
      node_js: '8'
      before_install: skip
      install:
        - npm install -g npm@$NPM_VERSION
        - npm ci
      script:
        - npm run build
        - npm run semantic-release
      after_success: skip

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
