version: '{build}'

platform:
  - x64

cache:
  - '%APPDATA%\npm-cache'

environment:
  matrix:
    - {PHP_VERSION: '7.0.13', VC_VERSION: '14', XDEBUG_VERSION: '2.5.0'}
    - {PHP_VERSION: '7.0.13', VC_VERSION: '14', XDEBUG_VERSION: '2.4.1'}
    - {PHP_VERSION: '5.6.28', VC_VERSION: '11', XDEBUG_VERSION: '2.5.0'}
    - {PHP_VERSION: '5.6.28', VC_VERSION: '11', XDEBUG_VERSION: '2.4.1'}
    - {PHP_VERSION: '5.6.28', VC_VERSION: '11', XDEBUG_VERSION: '2.3.3'}
    - {PHP_VERSION: '5.4.45', VC_VERSION:  '9', XDEBUG_VERSION: '2.4.1'}
    - {PHP_VERSION: '5.4.45', VC_VERSION:  '9', XDEBUG_VERSION: '2.3.3'}
    - {PHP_VERSION: '5.4.45', VC_VERSION:  '9', XDEBUG_VERSION: '2.2.3'}  # XDebug version on Vagrant

install:
  - ps: . .\appveyor-install.ps1

build_script:
  - npm run compile --silent

test_script:
  - npm run lint --silent
  - npm test --silent
